### ISSUE TITLE
How compare two excel files xlsx on the server? 

### ISSUE THREAD

**Issue by NavidHelp** [fileformat-free-consulting/projects#1]
A script download product details from the supplier and creates an xlsx file and they are hosted on my server.
It's a shared hosting with the latest PHP7
Uploading the file with all details and images on my online shop is very time consuming and takes all the server resources, so the site becomes incredibly slow.
If I could upload only the changes than the update would take only few minutes instead of several hours.
[products-20201016-0400.xlsx](https://github.com/fileformat-free-consulting/projects/files/5395037/products-20201016-0400.xlsx)
[products-20201017-0400.xlsx](https://github.com/fileformat-free-consulting/projects/files/5395038/products-20201017-0400.xlsx)
How to automate the creation of an update xlsx file with just changes?
Thanks

**Comment by tilalahmad** [comment]
@NavidHelp 

The [GroupDocs.Comparison Cloud SDK for PHP](https://docs.groupdocs.cloud/comparison/compare-documents/) provides a feature to track changes between source and target Excel document. However, unfortunately, the API is not working with your shared Excel files at the moment. We have logged a ticket in our issue tracking system for investigation and resolution of the issue. We will notify you as soon as it is resolved. 

You can also post your query in [groupdocs.cloud support forum](https://forum.groupdocs.cloud/c/comparison) to keep track of the issue yourself.
