### ISSUE TITLE
I want to create/build a image rating system for my created designs 2d and 3d both

### ISSUE THREAD

**Issue by anubhavhere** [fileformat-free-consulting/projects#2]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to GroupDocs APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.groupdocs.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>
Sir, I have lots of prints in the form of images, 2d and 3d , i want the user to rate the same as per his or her capacity for rewards.

< which platform you're working on -- operating system, development environment etc.>  i am working on wordpress php but i am open for python also

<attach input [documents>]
![Black M Hoodie_M9609_1576330090](https://user-images.githubusercontent.com/7204610/105640642-20edc400-5ea5-11eb-8735-a5b7b15fb751.jpg)
![Melange Grey M Hoodie_M9609_1576330090](https://user-images.githubusercontent.com/7204610/105640643-221ef100-5ea5-11eb-958d-1462fccbf304.jpg)
![Navy Blue M Hoodie_M9609_1576330090](https://user-images.githubusercontent.com/7204610/105640644-22b78780-5ea5-11eb-956e-fe55d5d1ab52.jpg)

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by shahzad-latif** [comment]
@anubhavhere ,

Our APIs only help  [create, edit, convert, or process various file formats](https://www.aspose.com/) in various programming languages including C#, Java, .NET, C++, and many open source languages on different platforms including Windows, Linux, and MacOS. 

In the above requirement, there is nothing which is specifically related to files processing, so I'm afraid we won't be able to help much in this case. If you have particular requirements related to above, you can let us know and also [contact our support team via our Free Forum Support](https://forum.aspose.com). I'm going to close this ticket for now.
