### ISSUE TITLE
NPIO

### ISSUE THREAD

**Issue by auntiejack56** [fileformat-free-consulting/projects#3]
I have built an Access runtime application for a client. The Access Runtime is the MS app which lets clients run my Access app without needing an Office license. 
The app and its vba is all fine, but it cannot create Excel spreadsheets because there is no Excel licence on the machines where this app will run. 
Can NPOI be adapted for use by VBA? I tried to build it in VS, but I don't know which of the solutions to build or how to allow COM usage.
Thanks,
Jack

**Comment by shahzad-latif** [comment]
@auntiejack56 

Sorry we haven't used NPOI with VBA. Why not use NPOI for .NET directly with your .NET appllication? It doesn't require Excel to be installed or have license for Excel or Office for that matter.
