### ISSUE TITLE
can you help with azure?

### ISSUE THREAD

**Issue by ruderod** [fileformat-free-consulting/projects#6]
trying to build an azure project in c#

**Comment by asadalikhan90** [comment]
@ruderod 

Would you please share a bit more details like which Aspose API you want to use and what type of issue you are facing? We will further proceed to assist you accordingly.

PS: In case you are facing some issue with any Aspose API, recommended place to report it is the dedicated [official Aspose Support forum](https://forum.aspose.com/) where you can please create a topic.
