### ISSUE TITLE
I want to create/build openxlsx for c++

### ISSUE THREAD

**Issue by HosseinBorhani** [fileformat-free-consulting/projects#7]
dear sir/madam
how can I use Openxlsx in my c++ project to save my data in various worksheet of an excel file?

**Comment by amjad-sahi** [comment]
@HosseinBorhani,

You may use [Aspose.Cells for C++](https://products.aspose.com/cells/cpp/) which is a native C++ library to create, manipulate and convert MS Excel spreadsheets (XLS, XLSX, XSLM, XLSB, etc.) programmatically without requiring Office Automation or Microsoft Excel application. You can also render images from worksheets and convert MS Excel spreadsheet to PDF format. The API also allows you to create, manipulate and render charts and shapes as well. Moreover, formula calculations is another good aspect provided by component and you may utilize it.

You can easily accomplish your task, i.e., create a new Open Office XML (XLSX) file and add/input or import data to different worksheets and finally save the Excel file. We recommend  you to kindly go through the Aspose.Cells for C++ [documentation](https://docs.aspose.com/cells/cpp/developer-guide/) which has example codes on how to use the APIs to perform different tasks. Moreover, you can download the [demos](https://github.com/aspose-cells/Aspose.Cells-for-C) project to view/browse and run the ready to run examples for your reference. You can also check the [API Reference Pages](https://reference.aspose.com/cells/cpp) to know more about the APIs.

Give it a try by downloading the Aspose.Cells for C++ from the [Downloads](https://releases.aspose.com/cells/cpp/) section.

Should you have further queries or comments, feel free to write us back. You can also reach us in the dedicated [forum](https://forum.aspose.com/c/cells/9). We handle our clients efficiently in the forums.
