### ISSUE TITLE
支持向word文档中写入图表吗 折线图、扇形图等等 want to create/build 

### ISSUE THREAD

**Issue by weiGaoCheng** [fileformat-free-consulting/projects#9]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to GroupDocs APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.groupdocs.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by shakeel-faiz** [comment]
是的，GroupDocs API 支持创建图表。但是，有关它的详细信息和示例代码，请通过此链接在论坛中发布您的问题。

https://forum.groupdocs.com/
